# Generated by Django 4.2 on 2023-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('calificacion', models.CharField(max_length=1)),
                ('contrasena', models.CharField(max_length=20)),
                ('id_taller', models.CharField(max_length=4)),
            ],
        ),
    ]
