# Generated by Django 4.2 on 2023-05-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyects',
            new_name='Projects',
        ),
    ]
